<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.healthnlp</groupId>
        <artifactId>langgraph-timelines</artifactId>
        <version>1.0.0</version>
    </parent>
    <name>LangGraph Timelines Bin</name>
    <description>A LangGraph-based pipeline for extracting and normalizing temporal information from clinical/patient notes using fine-tuned LLMs.</description>
    <organization>
        <name>HealthNLP</name>
        <url>https://github.com/HealthNLPorg</url>
    </organization>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <artifactId>lg-timelines-bin</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.healthnlp</groupId>
            <artifactId>lg-timelines-j</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.healthnlp</groupId>
            <artifactId>lg-timelines-py</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.healthnlp</groupId>
            <artifactId>pbj-langgraph-py</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.healthnlp</groupId>
            <artifactId>pbj-llm-tools-py</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bundle-project-sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/bin.xml</descriptor>
                            </descriptors>
                            <!-- Tar package is only compatible with gnu tar, many file have more
                      than 100 chars. Right now only javadoc files are too long. -->
                            <tarLongFileMode>gnu</tarLongFileMode>
                            <finalName>lg-timelines-${project.version}</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


</project>